Repository marigold-dev/tzsafe-ui, pull requests merged in 2023-04, with the labels that each got.

#60 [Refactor] Proposal duration
  assets/images/TzSafe.svg
  components/Banner.tsx
  components/create/aliases.tsx
  components/create/createLoader.tsx
  components/import/aliases.tsx
  components/import/basic.tsx
  components/navbar.tsx
  components/signersForm.tsx
  context/formContext.ts
  package-lock.json
  package.json
  pages/_app.tsx
  tests/adaptativeTime.test.ts
  utils/adaptiveTime.ts
  vitest.config.js
Labels: enhancement

#61 [Fix] Making a nice responsive on every page
  components/Alias.tsx
  components/ProposalCard.tsx
  components/Sidebar.tsx
  components/create/aliases.tsx
  components/create/basic.tsx
  components/footer.tsx
  components/formUtils.tsx
  components/import/aliases.tsx
  components/import/basic.tsx
  components/links.tsx
  components/navbar.tsx
  components/proposalSignForm.tsx
  components/renderError.tsx
  components/signersForm.tsx
  components/topUpForm.tsx
  components/transferForm.tsx
  context/config.ts
  pages/_app.tsx
  pages/address-book.tsx
  pages/history.tsx
  pages/index.tsx
  pages/proposals.tsx
Labels: enhancement

#64 [Feat] Documentation in sidebar
  components/Sidebar.tsx
Labels: enhancement

#63 [Refactor] contract execution refactor
  components/ContractExecution.tsx
  components/transferForm.tsx
  context/contractExecution.ts
  package-lock.json
  package.json
  utils/contractParam.ts
Labels: bug, enhancement

#65 [Fix] fail to pass env
  Dockerfile
Labels: bug

#68 [fix] fix passing wrong env
  .github/workflows/build_tzsafe.yml
Labels: bug
